name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: | 
        cd "$(git rev-parse --show-toplevel)"
        docker build . --file simple-spring-boot/Dockerfile --tag codetron/simple-spring-boot-ci:$(date +%s)docker build . --file ../simple-spring-boot/Dockerfile --tag codetron/simple-spring-boot-ci:$(date +%s)
