name: Docker Image CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Step 1: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Execute test
      - name: Run tests with Maven
        run: mvn test -f simple-spring-boot/pom.xml

      # Step 2: Extract version from pom.xml
      - name: Extract version from pom.xml
        id: extract_version
        run: |
          VERSION=$(mvn -f simple-spring-boot/pom.xml help:evaluate -Dexpression=project.version -q -DforceStdout | tr -d '\r')
          echo "Extracted VERSION: '$VERSION'"
          if [[ -z "$VERSION" ]]; then
            echo "Version extraction failed"
            exit 1
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      # Step 3: Determine the tag based on the branch or PR
      - name: Set Docker tag
        id: set_tag
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          if [[ $GITHUB_EVENT_NAME == "pull_request" ]]; then
            TAG="${{ env.VERSION }}-pr-${{ github.event.pull_request.number }}"
          else
            TAG="${{ env.VERSION }}-${BRANCH_NAME}"
          fi
          echo "TAG=${TAG}" >> $GITHUB_ENV

      # Step 4: Build Docker image
      - name: Build Docker image
        run: |
          docker build -f simple-spring-boot/Dockerfile -t codetron/simple-spring-boot-ci:${{ env.TAG }} simple-spring-boot

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Step 6: Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push codetron/simple-spring-boot-ci:${{ env.TAG }}
