name: Docker Image CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Step 1: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Step 2: Define image tag
      - name: Define image tag
        id: define_tag
        run: echo "TAG=$(date +%s)" >> $GITHUB_ENV

      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          cd "$(git rev-parse --show-toplevel)"
          docker build -f simple-spring-boot/Dockerfile -t codetron/simple-spring-boot-ci:${{ env.TAG }} simple-spring-boot

      # Step 4: List Docker images (to verify if the image exists)
      - name: List Docker images
        run: docker images

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Step 6: Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push codetron/simple-spring-boot-ci:${{ env.TAG }}
